### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by joeblew99** [minio/minio-xl#22]
Erasure code looks useful.

On my last project, i was involved with Machine Learning on Electrical grids. We hit 4 Petabytes per month - lots of storage but also bandwidth. We were sampling the data at the sample frequency of the AC grid, and its lots of data.
We then ran our code on that data, but could not through it away, because with ML, you need to be able to rerun the old data again as your system learns new things. Its only by rerunning on the old data that you can build the basis for the future, and the more data from the past, the better your prediction models work. 
I call it "deja vu" learning. Yes its not funny.

So does it only run on special intel servers. Its a special chip ? Can it run on an intel NUC for example ?

In relation to immutable data, its perfect for machne learning, because this is data you never ever want to change, you just want to add to it.

Then there is the fact that this data is then pushed into time series style DB's, to do aggregates, etc. Thats perfect again for immutable because you are always moving forward.

For counters its terrible, but thats ok.

then i am wondering about if you can delete the data. Say you only want to keep 6 months of raw data from the Grid project. Can you kill data, and if you do, do you need to rebalance your storage cluster.

--- Read
Can i read data from many data serves such that i can ask for a file, but each of my middle tier servers (say 100 of them), get 1/100th of the data still ? 

-- Write
So then i need to write the data from those 100 servers. But they will all be writing to a single file on the storage Cluster. Can they do this ? There needs to be either preallocation of disk space, and each fills a slot ? I ask this because network IO between storage and compute would kill me otherwise.
Can i see the mapping between compute and storage, so that at the compute side, i can arrange each server to write to the correct storage node as a big transaction, rather than have to go through a controller and then kill the Network IO.

Thanks in advance...

**Comment by abperiasamy** [comment]
Hi Joe, "deja vu" machine learning sounds cool. We are going to converge minio and minio-xl back into one code base. Next 2-3  months, server will go through a lot of changes. 

Minio is designed for storing unstructured data. You can start as small as few GBs and as large as 100+ PBs. We are adopting micro-storage architecture to achieve scale. Instead of creating one very large distributed server, Minio will create many smaller manageable cells. This way, failure domain is small and manageable. It is advisable for each cell to limit capacity to a max of 64TB (usable space after 8x8 erasure code). With the micro-storage architecture, you can add as many cells you need.

If you are using NUCs on the computational side, Minio client libraries or AWS S3 SDK has no specific client requirements. 

You may run Minio server on the NUCs too. Core i3 and i5 processors have AVX and SSE extensions which gives a boost tp erasure coding and SHA computations. NUCs are tiny. You wont be able to pack sufficient number of disks to reach Petabytes in capacity. I usually recommend 2U servers with 12x3.5" 4TB or 6TB HDDs, 10GigE, 64GB and Xeon E3 or E5 CPUs. 

Server supports both partial get and put operations. You can download or upload a large object in parallel from many clients. Server will verify the MD5SUM of individual parts and commit as one large object in the end. Minio client library upload large objects in parts using this approach already. You will need access to its lower level APIs to be able to upload from many clients. 

Controller is just a lock server. It am thinking of eliminating the controller all together. Reads and writes are always spread across the servers. Each server is equally capable.  Yes, for counters, it is better to use something like Redis. 

Pls ping me on our [gitter channel](gitter.minio.io). We can discuss more.

**Comment by joeblew99** [comment]
i am on glitter
